In [5]:
import pandas as pd 
import csv 
import matplotlib.pyplot as plt
import seaborn as sns 
import numpy as np
from us_state_abbrev import us_state_abbrev

In [6]:
federal_df = pd.read_csv("2007-2016-Homelessnewss-USA.csv")
state_df = pd.read_csv("Population-by-state.csv")

In [7]:
federal_df

,Year,State,CoC Number,CoC Name,Measures,Count
0,1/1/2007,AK,AK-500,Anchorage CoC,Chronically Homeless Individuals,224
1,1/1/2007,AK,AK-500,Anchorage CoC,Homeless Individuals,696
2,1/1/2007,AK,AK-500,Anchorage CoC,Homeless People in Families,278
3,1/1/2007,AK,AK-500,Anchorage CoC,Sheltered Chronically Homeless Individuals,187
4,1/1/2007,AK,AK-500,Anchorage CoC,Sheltered Homeless,842
5,1/1/2007,AK,AK-500,Anchorage CoC,Sheltered Homeless Individuals,589
6,1/1/2007,AK,AK-500,Anchorage CoC,Sheltered Homeless People in Families,253
7,1/1/2007,AK,AK-500,Anchorage CoC,Total Homeless,974
8,1/1/2007,AK,AK-500,Anchorage CoC,Unsheltered Chronically Homeless Individuals,37
9,1/1/2007,AK,AK-500,Anchorage CoC,Unsheltered Homeless,132
10,1/1/2007,AK,AK-500,Anchorage CoC,Unsheltered Homeless Individuals,107
11,1/1/2007,AK,AK-500,Anchorage CoC,Unsheltered Homeless People in Families,25
12,1/1/2007,AK,AK-501,Alaska Balance of State CoC,Chronically Homeless Individuals,54
13,1/1/2007,AK,AK-501,Alaska Balance of State CoC,Homeless Individuals,366
14,1/1/2007,AK,AK-501,Alaska Balance of State CoC,Homeless People in Families,302
15,1/1/2007,AK,AK-501,Alaska Balance of State CoC,Sheltered Chronically Homeless Individuals,34
16,1/1/2007,AK,AK-501,Alaska Balance of State CoC,Sheltered Homeless,545
17,1/1/2007,AK,AK-501,Alaska Balance of State CoC,Sheltered Homeless Individuals,302
18,1/1/2007,AK,AK-501,Alaska Balance of State CoC,Sheltered Homeless People in Families,243
19,1/1/2007,AK,AK-501,Alaska Balance of State CoC,Total Homeless,668
20,1/1/2007,AK,AK-501,Alaska Balance of State CoC,Unsheltered Chronically Homeless Individuals,20
21,1/1/2007,AK,AK-501,Alaska Balance of State CoC,Unsheltered Homeless,123
22,1/1/2007,AK,AK-501,Alaska Balance of State CoC,Unsheltered Homeless Individuals,64
23,1/1/2007,AK,AK-501,Alaska Balance of State CoC,Unsheltered Homeless People in Families,59
24,1/1/2007,AL,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",Chronically Homeless Individuals,516
25,1/1/2007,AL,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",Homeless Individuals,"1,529"
26,1/1/2007,AL,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",Homeless People in Families,575
27,1/1/2007,AL,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",Sheltered Chronically Homeless Individuals,269
28,1/1/2007,AL,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",Sheltered Homeless,"1,240"
29,1/1/2007,AL,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",Sheltered Homeless Individuals,833
...,...,...,...,...,...,...
86499,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Parenting Youth Under 18,0
86500,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Sheltered Children of Parenting Youth,14
86501,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Sheltered Chronically Homeless,33
86502,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Sheltered Chronically Homeless Individuals,29
86503,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Sheltered Chronically Homeless People in Families,4
86504,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Sheltered Homeless,491
86505,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Sheltered Homeless Individuals,277
86506,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Sheltered Homeless People in Families,214
86507,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Sheltered Homeless Unaccompanied Children (Und...,1
86508,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Sheltered Homeless Unaccompanied Young Adults ...,23
86509,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Sheltered Homeless Unaccompanied Youth (Under 25),24
86510,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Sheltered Homeless Veterans,56
86511,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Sheltered Parenting Youth (Under 25),12
86512,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Sheltered Parenting Youth Age 18-24,12
86513,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Sheltered Parenting Youth Under 18,0
86514,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Total Homeless,857
86515,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Children of Parenting Youth,3
86516,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Chronically Homeless,58
86517,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Chronically Homeless Individuals,51
86518,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Chronically Homeless People in Fam...,7
86519,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Homeless,366
86520,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Homeless Individuals,240
86521,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Homeless People in Families,126
86522,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Homeless Unaccompanied Children (U...,2
86523,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Homeless Unaccompanied Young Adult...,5
86524,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Homeless Unaccompanied Youth (Unde...,7
86525,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Homeless Veterans,31
86526,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Parenting Youth (Under 25),3
86527,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Parenting Youth Age 18-24,3
86528,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Parenting Youth Under 18,0

In [8]:
state_df

,GEO.id,GEO.id2,GEO.display-label,rescen42010,resbase42010,respop72010,respop72011,respop72012,respop72013,respop72014,respop72015,respop72016
0,Id,Id2,Geography,"April 1, 2010 - Census","April 1, 2010 - Estimates Base",Population Estimate (as of July 1) - 2010,Population Estimate (as of July 1) - 2011,Population Estimate (as of July 1) - 2012,Population Estimate (as of July 1) - 2013,Population Estimate (as of July 1) - 2014,Population Estimate (as of July 1) - 2015,Population Estimate (as of July 1) - 2016
1,0400000US01,1,Alabama,4779736,4780131,4785492,4799918,4815960,4829479,4843214,4853875,4863300
2,0400000US02,2,Alaska,710231,710249,714031,722713,731089,736879,736705,737709,741894
3,0400000US04,4,Arizona,6392017,6392301,6408312,6467163,6549634,6624617,6719993,6817565,6931071
4,0400000US05,5,Arkansas,2915918,2916025,2921995,2939493,2950685,2958663,2966912,2977853,2988248
5,0400000US06,6,California,37253956,37254522,37332685,37676861,38011074,38335203,38680810,38993940,39250017
6,0400000US08,8,Colorado,5029196,5029324,5048644,5118360,5189867,5267603,5349648,5448819,5540545
7,0400000US09,9,Connecticut,3574097,3574114,3579899,3589893,3593795,3596003,3591873,3584730,3576452
8,0400000US10,10,Delaware,897934,897936,899816,907924,916993,925395,934948,944076,952065
9,0400000US11,11,District of Columbia,601723,601766,605183,620477,635327,649165,659005,670377,681170
10,0400000US12,12,Florida,18801310,18804592,18849098,19096952,19344156,19582022,19888741,20244914,20612439
11,0400000US13,13,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
12,0400000US15,15,Hawaii,1360301,1360301,1363945,1377864,1391820,1406481,1416349,1425157,1428557
13,0400000US16,16,Idaho,1567582,1567650,1571010,1584143,1595911,1612011,1633532,1652828,1683140
14,0400000US17,17,Illinois,12830632,12831574,12841578,12860012,12870798,12879505,12867544,12839047,12801539
15,0400000US18,18,Indiana,6483802,6484136,6490528,6516480,6537743,6569102,6595233,6612768,6633053
16,0400000US19,19,Iowa,3046355,3046869,3050738,3065223,3076310,3091930,3108030,3121997,3134693
17,0400000US20,20,Kansas,2853118,2853129,2858850,2869503,2885262,2892821,2899360,2906721,2907289
18,0400000US21,21,Kentucky,4339367,4339344,4348662,4369354,4384799,4400477,4413057,4424611,4436974
19,0400000US22,22,Louisiana,4533372,4533479,4544996,4575404,4603429,4626402,4647880,4668960,4681666
20,0400000US23,23,Maine,1328361,1328364,1327730,1328231,1328895,1329076,1330719,1329453,1331479
21,0400000US24,24,Maryland,5773552,5773786,5788584,5843603,5889651,5931129,5967295,5994983,6016447
22,0400000US25,25,Massachusetts,6547629,6547813,6565524,6611923,6658008,6706786,6749911,6784240,6811779
23,0400000US26,26,Michigan,9883640,9884129,9877495,9876213,9887238,9898982,9915767,9917715,9928300
24,0400000US27,27,Minnesota,5303925,5303924,5311147,5348562,5380285,5418521,5453109,5482435,5519952
25,0400000US28,28,Mississippi,2967297,2968103,2970322,2978162,2984945,2990482,2992400,2989390,2988726
26,0400000US29,29,Missouri,5988927,5988928,5996118,6010717,6025415,6042711,6060930,6076204,6093000
27,0400000US30,30,Montana,989415,989414,990641,997821,1005196,1014314,1022867,1032073,1042520
28,0400000US31,31,Nebraska,1826341,1826334,1830051,1842283,1855725,1868559,1881145,1893765,1907116
29,0400000US32,32,Nevada,2700551,2700691,2703284,2718379,2752565,2786464,2833013,2883758,2940058
30,0400000US33,33,New Hampshire,1316470,1316461,1316872,1318473,1321182,1322687,1328743,1330111,1334795
31,0400000US34,34,New Jersey,8791894,8791953,8803729,8841243,8873211,8899162,8925001,8935421,8944469
32,0400000US35,35,New Mexico,2059179,2059198,2064756,2077756,2083784,2085193,2083024,2080328,2081015
33,0400000US36,36,New York,19378102,19378110,19402640,19519529,19602769,19673546,19718515,19747183,19745289
34,0400000US37,37,North Carolina,9535483,9535688,9558915,9650963,9746175,9841590,9934399,10035186,10146788
35,0400000US38,38,North Dakota,672591,672591,674526,685476,702087,724019,739904,756835,757952
36,0400000US39,39,Ohio,11536504,11536727,11540983,11544824,11550839,11570022,11594408,11605090,11614373
37,0400000US40,40,Oklahoma,3751351,3751615,3759603,3786274,3817054,3852415,3877499,3907414,3923561
38,0400000US41,41,Oregon,3831074,3831072,3838048,3868031,3899116,3925751,3968371,4024634,4093465
39,0400000US42,42,Pennsylvania,12702379,12702857,12712343,12744293,12771854,12781338,12790565,12791904,12784227
40,0400000US44,44,Rhode Island,1052567,1052940,1053337,1052451,1052901,1053033,1054480,1055607,1056426
41,0400000US45,45,South Carolina,4625364,4625410,4635943,4672637,4720760,4767894,4828430,4894834,4961119
42,0400000US46,46,South Dakota,814180,814195,816325,824398,834441,844922,852561,857919,865454
43,0400000US47,47,Tennessee,6346105,6346298,6356671,6397634,6454306,6494821,6544663,6595056,6651194
44,0400000US48,48,Texas,25145561,25146100,25244310,25646389,26071655,26473525,26944751,27429639,27862596
45,0400000US49,49,Utah,2763885,2763888,2775326,2816124,2855782,2902663,2941836,2990632,3051217
46,0400000US50,50,Vermont,625741,625741,625982,626730,626444,627140,626984,626088,624594
47,0400000US51,51,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
48,0400000US53,53,Washington,6724540,6724545,6743226,6822520,6895226,6968006,7054196,7160290,7288000
49,0400000US54,54,West Virginia,1852994,1853011,1854230,1854972,1856560,1853231,1848514,1841053,1831102
50,0400000US55,55,Wisconsin,5686986,5687289,5690263,5709640,5726177,5742854,5758377,5767891,5778708
51,0400000US56,56,Wyoming,563626,563767,564513,567725,576765,582684,583642,586555,585501
52,0400000US72,72,Puerto Rico,3725789,3726157,3721525,3678732,3634488,3593077,3534874,3473181,3411307

In [9]:
state_df.columns = state_df.iloc[0]
state_df.head()

,Id,Id2,Geography,"April 1, 2010 - Census","April 1, 2010 - Estimates Base",Population Estimate (as of July 1) - 2010,Population Estimate (as of July 1) - 2011,Population Estimate (as of July 1) - 2012,Population Estimate (as of July 1) - 2013,Population Estimate (as of July 1) - 2014,Population Estimate (as of July 1) - 2015,Population Estimate (as of July 1) - 2016
0,Id,Id2,Geography,"April 1, 2010 - Census","April 1, 2010 - Estimates Base",Population Estimate (as of July 1) - 2010,Population Estimate (as of July 1) - 2011,Population Estimate (as of July 1) - 2012,Population Estimate (as of July 1) - 2013,Population Estimate (as of July 1) - 2014,Population Estimate (as of July 1) - 2015,Population Estimate (as of July 1) - 2016
1,0400000US01,1,Alabama,4779736,4780131,4785492,4799918,4815960,4829479,4843214,4853875,4863300
2,0400000US02,2,Alaska,710231,710249,714031,722713,731089,736879,736705,737709,741894
3,0400000US04,4,Arizona,6392017,6392301,6408312,6467163,6549634,6624617,6719993,6817565,6931071
4,0400000US05,5,Arkansas,2915918,2916025,2921995,2939493,2950685,2958663,2966912,2977853,2988248

In [12]:
state_df = state_df.reindex(state_df.index.drop(0))

KeyError: '[0] not found in axis'

In [ ]:
state_df.head()

In [18]:
state_df["Geograpy"] = state_df["Geography"].map(us_state_abbrev)

In [20]:
state_df = state_df.rename(columns={"Geograpy":"State", "Geography":"StateFull"})

In [21]:
state_df.head()

,Id,Id2,StateFull,"April 1, 2010 - Census","April 1, 2010 - Estimates Base",Population Estimate (as of July 1) - 2010,Population Estimate (as of July 1) - 2011,Population Estimate (as of July 1) - 2012,Population Estimate (as of July 1) - 2013,Population Estimate (as of July 1) - 2014,Population Estimate (as of July 1) - 2015,Population Estimate (as of July 1) - 2016,State
1,0400000US01,1,Alabama,4779736,4780131,4785492,4799918,4815960,4829479,4843214,4853875,4863300,AL
2,0400000US02,2,Alaska,710231,710249,714031,722713,731089,736879,736705,737709,741894,AK
3,0400000US04,4,Arizona,6392017,6392301,6408312,6467163,6549634,6624617,6719993,6817565,6931071,AZ
4,0400000US05,5,Arkansas,2915918,2916025,2921995,2939493,2950685,2958663,2966912,2977853,2988248,AR
5,0400000US06,6,California,37253956,37254522,37332685,37676861,38011074,38335203,38680810,38993940,39250017,CA

In [ ]:
from sqlalchemy import create_engine
from sqlconfig import password
import pymysql
pymysql.install_as_MySQLdb()

engine = create_engine(f'mysql://root:{password}@localhost:3306/homelesscensus')

In [1]:
state_df.to_sql("players_penalties", con=engine, if_exists='replace')

NameError: name 'state_df' is not defined

In [13]:
streamdf = federal_df.loc[federal_df["State"]=="AZ"]

In [14]:
streamdf

,Year,State,CoC Number,CoC Name,Measures,Count
228,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Chronically Homeless Individuals,425
229,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Homeless Individuals,"2,235"
230,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Homeless People in Families,762
231,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Chronically Homeless Individuals,93
232,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless,"1,013"
233,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless Individuals,532
234,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless People in Families,481
235,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Total Homeless,"2,997"
236,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Chronically Homeless Individuals,332
237,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless,"1,984"
238,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless Individuals,"1,703"
239,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless People in Families,281
240,1/1/2007,AZ,AZ-501,Tucson/Pima County CoC,Chronically Homeless Individuals,890
241,1/1/2007,AZ,AZ-501,Tucson/Pima County CoC,Homeless Individuals,"2,258"
242,1/1/2007,AZ,AZ-501,Tucson/Pima County CoC,Homeless People in Families,943
243,1/1/2007,AZ,AZ-501,Tucson/Pima County CoC,Sheltered Chronically Homeless Individuals,150
244,1/1/2007,AZ,AZ-501,Tucson/Pima County CoC,Sheltered Homeless,"2,010"
245,1/1/2007,AZ,AZ-501,Tucson/Pima County CoC,Sheltered Homeless Individuals,"1,159"
246,1/1/2007,AZ,AZ-501,Tucson/Pima County CoC,Sheltered Homeless People in Families,851
247,1/1/2007,AZ,AZ-501,Tucson/Pima County CoC,Total Homeless,"3,201"
248,1/1/2007,AZ,AZ-501,Tucson/Pima County CoC,Unsheltered Chronically Homeless Individuals,740
249,1/1/2007,AZ,AZ-501,Tucson/Pima County CoC,Unsheltered Homeless,"1,191"
250,1/1/2007,AZ,AZ-501,Tucson/Pima County CoC,Unsheltered Homeless Individuals,"1,099"
251,1/1/2007,AZ,AZ-501,Tucson/Pima County CoC,Unsheltered Homeless People in Families,92
252,1/1/2007,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Chronically Homeless Individuals,"1,489"
253,1/1/2007,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Homeless Individuals,"5,527"
254,1/1/2007,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Homeless People in Families,"2,921"
255,1/1/2007,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Chronically Homeless Individuals,407
256,1/1/2007,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Homeless,"5,595"
257,1/1/2007,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Homeless Individuals,"2,732"
...,...,...,...,...,...,...
70455,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Parenting Youth Under 18,0
70456,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Children of Parenting Youth,143
70457,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Chronically Homeless,332
70458,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Chronically Homeless Individuals,296
70459,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Chronically Homeless People in Families,36
70460,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Homeless,"4,056"
70461,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Homeless Individuals,"1,980"
70462,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Homeless People in Families,"2,076"
70463,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Homeless Unaccompanied Children (Und...,60
70464,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Homeless Unaccompanied Young Adults ...,200
70465,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Homeless Unaccompanied Youth (Under 25),260
70466,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Homeless Veterans,319
70467,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Parenting Youth (Under 25),91
70468,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Parenting Youth Age 18-24,91
70469,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Sheltered Parenting Youth Under 18,0
70470,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Total Homeless,"5,702"
70471,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Unsheltered Children of Parenting Youth,0
70472,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Unsheltered Chronically Homeless,413
70473,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Unsheltered Chronically Homeless Individuals,413
70474,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Unsheltered Chronically Homeless People in Fam...,0
70475,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Unsheltered Homeless,"1,646"
70476,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Unsheltered Homeless Individuals,"1,640"
70477,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Unsheltered Homeless People in Families,6
70478,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Unsheltered Homeless Unaccompanied Children (U...,6
70479,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Unsheltered Homeless Unaccompanied Young Adult...,104
70480,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Unsheltered Homeless Unaccompanied Youth (Unde...,110
70481,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Unsheltered Homeless Veterans,131
70482,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Unsheltered Parenting Youth (Under 25),0
70483,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Unsheltered Parenting Youth Age 18-24,0
70484,1/1/2016,AZ,AZ-502,Phoenix/Mesa/Maricopa County Regional CoC,Unsheltered Parenting Youth Under 18,0

In [15]:
azbalancedf = streamdf.loc[streamdf["CoC Name"]=="Arizona Balance of State CoC"]

In [17]:
azbalancedf

,Year,State,CoC Number,CoC Name,Measures,Count
228,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Chronically Homeless Individuals,425
229,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Homeless Individuals,"2,235"
230,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Homeless People in Families,762
231,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Chronically Homeless Individuals,93
232,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless,"1,013"
233,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless Individuals,532
234,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless People in Families,481
235,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Total Homeless,"2,997"
236,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Chronically Homeless Individuals,332
237,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless,"1,984"
238,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless Individuals,"1,703"
239,1/1/2007,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless People in Families,281
5016,1/1/2008,AZ,AZ-500,Arizona Balance of State CoC,Chronically Homeless Individuals,408
5017,1/1/2008,AZ,AZ-500,Arizona Balance of State CoC,Homeless Individuals,"2,162"
5018,1/1/2008,AZ,AZ-500,Arizona Balance of State CoC,Homeless People in Families,778
5019,1/1/2008,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Chronically Homeless Individuals,76
5020,1/1/2008,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless,956
5021,1/1/2008,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless Individuals,459
5022,1/1/2008,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless People in Families,497
5023,1/1/2008,AZ,AZ-500,Arizona Balance of State CoC,Total Homeless,"2,940"
5024,1/1/2008,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Chronically Homeless Individuals,332
5025,1/1/2008,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless,"1,984"
5026,1/1/2008,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless Individuals,"1,703"
5027,1/1/2008,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless People in Families,281
9780,1/1/2009,AZ,AZ-500,Arizona Balance of State CoC,Chronically Homeless Individuals,409
9781,1/1/2009,AZ,AZ-500,Arizona Balance of State CoC,Homeless Individuals,"2,217"
9782,1/1/2009,AZ,AZ-500,Arizona Balance of State CoC,Homeless People in Families,"1,019"
9783,1/1/2009,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Chronically Homeless Individuals,98
9784,1/1/2009,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless,"1,172"
9785,1/1/2009,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless Individuals,589
...,...,...,...,...,...,...
70371,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Parenting Youth Under 18,1
70372,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Children of Parenting Youth,19
70373,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Chronically Homeless,43
70374,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Chronically Homeless Individuals,36
70375,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Chronically Homeless People in Families,7
70376,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless,"1,023"
70377,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless Individuals,658
70378,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless People in Families,365
70379,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless Unaccompanied Children (Und...,17
70380,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless Unaccompanied Young Adults ...,47
70381,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless Unaccompanied Youth (Under 25),64
70382,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Homeless Veterans,112
70383,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Parenting Youth (Under 25),15
70384,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Parenting Youth Age 18-24,14
70385,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Sheltered Parenting Youth Under 18,1
70386,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Total Homeless,"2,240"
70387,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Children of Parenting Youth,0
70388,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Chronically Homeless,394
70389,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Chronically Homeless Individuals,371
70390,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Chronically Homeless People in Fam...,23
70391,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless,"1,217"
70392,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless Individuals,"1,076"
70393,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless People in Families,141
70394,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless Unaccompanied Children (U...,1
70395,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless Unaccompanied Young Adult...,33
70396,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless Unaccompanied Youth (Unde...,34
70397,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Homeless Veterans,193
70398,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Parenting Youth (Under 25),0
70399,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Parenting Youth Age 18-24,0
70400,1/1/2016,AZ,AZ-500,Arizona Balance of State CoC,Unsheltered Parenting Youth Under 18,0

In [28]:
counts = [count for count in azbalancedf["Count"]]
streamfin = pd.DataFrame(columns=(["Year"],["Chronically Homeless Individuals"],["Homeless Individuals"],["Homeless People in Families"],["Sheltered Chronically Homeless Individuals"],["Sheltered Homeless"],["Sheltered Homeless Individuals"],["Sheltered Homeless People in Families"],["Total Homeless"],["Unsheltered Chronically Homeless Individuals"],["Unsheltered Homeless"],["Unsheltered Homeless Individuals"],["Unsheltered Homeless People in Families"]))

In [29]:
streamfin

Empty DataFrame
Columns: [(Year,), (Chronically Homeless Individuals,), (Homeless Individuals,), (Homeless People in Families,), (Sheltered Chronically Homeless Individuals,), (Sheltered Homeless,), (Sheltered Homeless Individuals,), (Sheltered Homeless People in Families,), (Total Homeless,), (Unsheltered Chronically Homeless Individuals,), (Unsheltered Homeless,), (Unsheltered Homeless Individuals,), (Unsheltered Homeless People in Families,)]
Index: []

In [53]:
countsrows = []
for k, v in enumerate(counts):
    countsrows.append(v)
    if k % 11 == 0 and k != 0:
        break

In [54]:
countsrows = []